#include <stdio.h>
#include "SUPEMON_GAME.h"

void loadGame(Player* player){
    // Load the game from a file
    // ...
    // Load the player's data
    // ...
    // Load the player's Supemons
    // ...
    // Load the player's items
    // ...
    // Load the player's progress
    // ...
    // Display a message to indicate that the game has been loaded
    printf("Game loaded successfully!\n");
}

void saveGame(Player* player){
    // Save the game to a file
    // ...
    // Save the player's data
    // ...
    // Save the player's Supemons
    // ...
    // Save the player's items
    // ...
    // Save the player's progress
    // ...
    // Display a message to indicate that the game has been saved
    printf("Game saved successfully!\n");
}